### ISSUE TITLE
Bitcoin/CLN Client: Repository Doesn't Exist

### ISSUE THREAD

**Issue by carlaKC** [scaling-lightning/scaling-lightning#14]
Running the example helm file: 
`./scaling-lightning start -f examples/helmfiles/helmfile.yaml `

Bitcoind and CLN get stuck in image pull: 
```
bitcoind-0   1/2     ImagePullBackOff   0 
cln2-0       1/2     ImagePullBackOff   2
```

Both with "repository doesn't exist" errors: 
```
Failed to pull image "bitcoind-client:latest": rpc error: code = Unknown desc = Error response from 
daemon: pull access denied for bitcoind-client, repository does not exist or may require 'docker 
login': denied: requested access to the resource is denied
```

```
Failed to pull image "cln-client:latest": rpc error: code = Unknown desc = Error response from 
daemon: pull access denied for cln-client, repository does not exist or may require 'docker 
login': denied: requested access to the resource is denied

```
(re-tried this logging into dockerhub and it doesn't help)

This is easily fixable by building the container locally, but it would be nice if the example worked out of the box!

**Comment by maxwedwards** [comment]
Thanks for the report, I hope this commit fixes the issue (https://github.com/scaling-lightning/scaling-lightning/commit/201db11863293b856fae2f911ed14f6c162ddd50).
