### ISSUE TITLE
Wallet out-of-sync when scaling lightning is running idle for a certain time.

### ISSUE THREAD

**Issue by 2Fast2BCn** [scaling-lightning/scaling-lightning#21]
An auto-mine of 1 block (every x seconds) would fix this issue.

**Comment by maxwedwards** [comment]
@2Fast2BCn thanks for the issue, will look at adding auto-mine.

**Comment by maxwedwards** [comment]
Feature added in `v0.3.0` and enabled by default. Set the value of `autoGen: false` in your helmfile to disable.

New block produced every 10 seconds. (Sending payment and opening channel already automatically generates blocks)

Could you test this release and see if it works for you @2Fast2BCn ?

**Comment by maxwedwards** [comment]
Closing as complete
