### ISSUE TITLE
docs links in main readme give 404

### ISSUE THREAD

**Issue by JssDWt** [scaling-lightning/scaling-lightning#24]
https://scalinglightning.com/docs/ does not exist currently.

**Comment by maxwedwards** [comment]
Thanks for the report, I assume that was from the readme?

There are docs but unfortunately no index page: https://scalinglightning.com/docs/project-use-cases

**Comment by maxwedwards** [comment]
Updated link in readme

**Comment by JssDWt** [comment]
@maxwedwards There's another link under the Gettinig Started header

**Comment by maxwedwards** [comment]
Good catch thanks.
