### ISSUE TITLE
Support of multiple kubernetes namespaces

### ISSUE THREAD

**Issue by Jhoyola** [scaling-lightning/scaling-lightning#29]
Currently the kubernetes namespace to be used is hardcoded to "sl". But it would be useful to be able to configure a different namespace optionally to be able to run multiple separated SLs in parallel. For example we need to have a local dev network, but also e2e tests for which the network is created and immediately destroyed once the test are finished.

@m3dwards Do you think it would be acceptable to do this? It doesn't seem like a very big task, so we could do it if you see no big problems with it. I'm thinking of adding the namespace in the SLNetwork struct and have the current "sl" as default, so maybe could even (mostly) keep backwards compatibility.

**Comment by m3dwards** [comment]
Yep, that sounds useful.

**Comment by Jhoyola** [comment]
Merged in https://github.com/scaling-lightning/scaling-lightning/pull/30
